#Bright Chidozie Onyekachi 
#To add adjective to the sentence.
adjective= input("Enter ANGRY")

#prompts the user to enter the animal name
Animal= input("Enter Monkey")

# Prompts User to add first verb
verb1= input("Enter shout")

#User adds exclamation
exclamation= input("Enter WOW")

#User adds the second verb
verb2= input("Enter dance")

#User adds the third verb
verb3= input("Enter escape");

#Strngs are stored in the variables below.
word= "The other day, I was really in trouble. It all started when I saw a very\n"+ adjective + Animal + verb1 +"down the hallway." + exclamation+ "! I yelled.\n "
word2= "But all I could think to do was to" + verb2 + "over and over. Miraculously,\n"
word3= "that caused it to stop, but not before it tried to" + verb3+ "right in front of my family."

#Outputing User inputs concantenanted with strings
print(word)
print(word2)
print(word3)
